# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3c65bdcf2731fb9e2da5e0e429b8c938c918e3fe98b2d4adb8208573801e7647c8e53b45cd6fa5f6b5910052f2ccd911c148129b9ff705a3f8a0d59a9949353

test:
  secret_key_base: 1fa1f0dc24834c4ce277cec0ce4c703e3213b4ef63f350dc94e91af688956c50bc048751b2080d7fbf1bbbcee35745f6798665e484e2b984b8f596edc30a5c04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
